<?php
$no = $_SESSION["edit"] ;
$member = Event::findFirst("id = '$no'");
?>

<?php echo $this->flashSession->output();?> 

<form action="" method="post" >
<center>
    <label>Event</label>
    <input type="text" class="form-control" placeholder="eventname" required name="eventname" id="eventname" value="<?php echo $member->eventname?>" >
    <br><label>Date</label>
    <input type="date" class="form-control" placeholder="mm/dd/yyyy" required name="eventdate" id="eventdate" value="<?php echo $member->eventdate?>">
    <br><label>Detail</label>
    <input type="text" class="form-control" placeholder="eventdetails" required rows="4" name="eventdetail" id="eventdetail" value="<?php echo $member->eventdetail?>"></input>
    <br><label>Picture</label>
    <div class="custom-file">
          <input type="file" name="photo" id="photo" class="custom-file-input"  value="<?php echo $member->eventpicture?>" >
          <label class="custom-file-label" >Choose file</label>
    </div>
    <?php if($member->eventpicture!=''){?>
   <div class="form-group">  
          <img style="width:100px; height:100px" src="<?php echo $this->url->getBaseUri().'public/img/'.$member->eventpicture; ?>">
  </div>
  <?php }?>
    <hr><button type="submit" class="btn btn-light">submit</button>
    <a href="<?php echo $this->url->getBaseUri(); ?>profile" class="btn btn-light">Back</a>
</center>
</form>